version: '3.8'

services:
  fastapi-api:
    build:
      context: ./api-app
    container_name: fastapi-api
    ports:
      - "8000:8000"
    volumes:
      - ./api-app/saved_images:/app/saved_images

  react-frontend:
    build:
      context: ./react-ui
      args:
        VITE_API_BASE_URL: http://20.235.180.208:8000
    container_name: react-frontend
    ports:
      - "3000:80"
