version: "3.8"

services:
  api:
    build:
      context: ./image-recognition-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./image-recognition-api/saved_images:/app/saved_images
      - ./image-recognition-api/uploads:/app/uploads
      - ./image-recognition-api/products:/app/products
      - ./image-recognition-api/planograms:/app/planograms
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./react-image-exchange-main
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - api
